theme: jekyll-theme-cayman
title: Rede Pela Democracia
description: "Baixe nossos manuais"
show_downloads: "true"
google_analytics: "UA-127555630-1"
manual:
  rede: https://www.dropbox.com/s/fkarpvda69ksrp7/MANUALRPD.pdf?dl=0
  rede_social: https://www.dropbox.com/s/t1mop9twbiuwa55/MANUALRPD_RS.pdf?dl=0 
  seguranca_whatsapp: https://www.dropbox.com/s/4kivg9maq2twm2r/SEGURAN%C3%87A%20NO%20WHATSAPP_final.pdf?dl=0
  another_url: Rede Pela Democracia
